name: Node.js CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation (Syntax Check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +

  gitleaks-scan:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1

  trivy_fs_scan:
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build_backend_docker_image_and_push:
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: adijaiswal/backend:latest
          file: ./api/Dockerfile

  build_frontend_docker_image_and_push:
    runs-on: ubuntu-latest
    needs: trivy_fs_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: adijaiswal/frontend:latest
          file: ./client/Dockerfile

  trivy_image_scan:
    runs-on: ubuntu-latest
    needs: build_frontend_docker_image_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy image scan for backend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: adijaiswal/backend:latest
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      - name: Run Trivy image scan for frontend
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: adijaiswal/frontend:latest
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

  update_cd_repo:
    runs-on: ubuntu-latest
    needs: trivy_image_scan
    env:
      IMAGE_TAG: ${{ github.sha }}
      CD_REPO: jaiswaladi246/3-Tier-GitOps-CD
      CD_BRANCH: main
    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CD_REPO }}
          ref: ${{ env.CD_BRANCH }}
          token: ${{ secrets.CD_REPO_TOKEN }}
          path: cd
      - name: Bump images
        run: |
          curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o yq && sudo install yq /usr/local/bin/yq
          yq -i '(.spec.template.spec.containers[]|select(.name=="backend")).image="adijaiswal/backend:"+env(IMAGE_TAG)'  cd/k8s/prod/backend-deploy.yaml
          yq -i '(.spec.template.spec.containers[]|select(.name=="frontend")).image="adijaiswal/frontend:"+env(IMAGE_TAG)' cd/k8s/prod/frontend-deploy.yaml
      - name: Commit & push directly
        working-directory: cd
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git commit -am "bump images to ${IMAGE_TAG}" || echo "no changes"
          git push
